### ISSUE TITLE
how do i get da pc port of wmw?

### ISSUE THREAD

**Issue by kkiijyui** [wmw-modding/wheres-my-editor#2]

**Comment by ego-lay-atman-bay** [comment]
Unfortunately the windows version is not supported, due to where the files are placed in the game.

**Comment by SuperHero2010** [comment]
Step 1: Download the game "Where's my water?" 
Step 2: Extract the game with WinRAR or 7zip 
Step 3: Go to the "wme.exe" application 
Step 4: Choose File/Settings (If the application automatically opens window explorer, skip step 4) 
Step 5: In the "Asset" line, select the game folder that you extracted in step 1 (If the application automatically opens window explorer, skip step 5)
Step 6: Click "Select Folder"
Step 7: Click "Ok" to save changes (If you have already selected the game folder, skip step 7)
Step 8: Exit the application and reopen the application.

**Comment by ego-lay-atman-bay** [comment]
Except it doesn''t''''' work for the windows version, because of the different file system.

**Comment by SuperHero2010** [comment]
I'm instructing "kkiijyui".

**Comment by ego-lay-atman-bay** [comment]
Yeah, except that was how to set up where's my editor, not the windows 10 version of where's my water (which I'm assuming that's what they meant by "pc port of wmw").

**Comment by SuperHero2010** [comment]
What??? "Where's my Water" is for Android. If you want to play on Windows 10, download WSA and WSA Pacman.

**Comment by ego-lay-atman-bay** [comment]
There was a windows 10 version, which you can find in the wmw wiki discord server (it's no longer available in the microsoft store). There was also a mac version, but it's older, and 32-bit, which modern macos does not support.

**Comment by SuperHero2010** [comment]
WSA and WSA Pacman is for Windows 10, not for Mac

**Comment by SuperHero2010** [comment]
Download in Github [Here](https://github.com/MustardChef/WSABuilds)

**Comment by ego-lay-atman-bay** [comment]
I know, I'm saying that there really were full wmw ports to windows 10 and mac, not emulators, actual full native ports. Both these versions can be downloaded [here](https://docs.google.com/document/d/1dHHg6RGVcpwjwlAEHxOLMvaS0QvObMofEI0O9xCskq8/edit?usp=drivesdk).

**Comment by SuperHero2010** [comment]
I know. But you're talking about choosing the type of game "Where's my Water?"  in "Where's my Editor?". What I mean is that WSA and WSA Pacman aren't for Mac.

**Comment by ego-lay-atman-bay** [comment]
Well the op was asking about the "pc port", and I have a feeling they already knew about the android and ios version. Of course this would all have been avoided if you actually said that you can't use the windows 10 version, only the android / ios version, then explained how to use those on pc. Just saying "Download the game" does not clear anything up.

**Comment by SuperHero2010** [comment]
Why are you so slow understand? I'm using Windows 10 and can install WSA and WSA Pacman. I also downloaded "Where's my Editor" and I used it 8 months ago. Did I not know?  I did create quite a few new levels. But when I save any Swampy level, Mystery Duck loses its "StarType". I had to edit it again so it took a lot of time. Please fix "Where's my Editor".

**Comment by ego-lay-atman-bay** [comment]
I do understand now after you actually said this

> I know. But you're talking about choosing the type of game "Where's my Water?" in "Where's my Editor?". What I mean is that WSA and WSA Pacman aren't for Mac.

I'm just saying you could've explained HOW to install wsa and wsa pacman, as well as where's my water, instead of just saying

> Step 1: Download the game "Where's my water?"

P.S. I'm actually also wondering how you got wmw to work in wsa, because last time I tried (on windows 10 at least), wmw wouldn't work (could be my cpu / gpu, but it could be something else).

**Comment by SuperHero2010** [comment]
WSA and WSA Pacman is for Windows 10 22H2 and Windows 11 (But I using Windows 10 2008). What version of Windows are you using?

**Comment by ego-lay-atman-bay** [comment]
Well, I just used https://github.com/MustardChef/WSABuilds/, and installed wmw via adb, I didn't know about wsa pacman (although judging by the name, I have a feeling it's just for installing apks, which I can already do with adb).

**Comment by ego-lay-atman-bay** [comment]
As for fixing wme, I don't think I'm going to, because I'm planning on creating a new editor, one that can work on android (although I haven't started yet...).

**Comment by SuperHero2010** [comment]
WSA Pacman install APK files into Windows 10 22H2 and Windows 11 (Windows Subsystem for Android is required for WSA Pacman to work)

**Comment by SuperHero2010** [comment]
Download WSA Pacman [Here](https://github.com/alesimula/wsa_pacman)

**Comment by SuperHero2010** [comment]
WHAT??? "Where's my Editor" FOR ANDROID???

**Comment by SuperHero2010** [comment]
YOU USE "adb" AND "Windows subsystem for Android" TO INSTALL "Where's my Water"?!?!?!?!?

**Comment by SuperHero2010** [comment]
It isn't possible to install "Where's my Water" on the computer if you use "adb" and "Windows subsystem for Android". You must use "Windows subsystem for Android" and "WSA Pacman" to install "Where's my Water".

**Comment by SuperHero2010** [comment]
No wonder you couldn't install "Where's my Water" last time.

**Comment by ego-lay-atman-bay** [comment]
> It isn't possible to install "Where's my Water" on the computer if you use "adb" and "Windows subsystem for Android".

No, it works, it's just not as user friendly as wsa pacman.

**Comment by SuperHero2010** [comment]
Um... Ok. So are you fixing the app?

**Comment by ego-lay-atman-bay** [comment]
Like I said, I'm going to be creating a new and better program, so I'm probably not gonna fix it. If you want to try and fix it yourself, go ahead, learn how to code in python, and submit a pull request, I might merge it.

I'm honestly just procrastinating, sorry.

**Comment by SuperHero2010** [comment]
Um.... I can't fix the app. But I can write json code.

**Comment by SuperHero2010** [comment]
I won't force you to fix it.  I just can't fix the app.

**Comment by SuperHero2010** [comment]
I use an .exe editing application. When I checked, I didn't understand what was in its code. So I can't edit the application.

**Comment by ego-lay-atman-bay** [comment]
The code for the app is in this repository, and it's written in python. You will not be able to get anywhere if you're trying to edit the exe.

**Comment by SuperHero2010** [comment]
Example: Resource Hacker, Resoource Tuner

**Comment by SuperHero2010** [comment]
In the repository description?

**Comment by ego-lay-atman-bay** [comment]
Don't use an exe editor, you're not gonna be able to do anything. Download the code in this repository (click on the code tab), and then follow the instructions in the readme to get it all setup.

**Comment by SuperHero2010** [comment]
In the repository description?

**Comment by ego-lay-atman-bay** [comment]
Yes

**Comment by SuperHero2010** [comment]
I don't see

**Comment by ego-lay-atman-bay** [comment]
In the "building" section
https://github.com/wmw-modding/wheres-my-editor?tab=readme-ov-file#building

**Comment by SuperHero2010** [comment]
I don't understand

**Comment by SuperHero2010** [comment]
Are those codes used to create installation files?

**Comment by ego-lay-atman-bay** [comment]
Yes

**Comment by SuperHero2010** [comment]
But... I can't because I was sleeping.

**Comment by ego-lay-atman-bay** [comment]
Ok.

**Comment by SuperHero2010** [comment]
I will try tomorrow morning.

**Comment by SuperHero2010** [comment]
Wait, before I went to sleep, I asked one last question: "Where can I download the "Python" application?"

**Comment by ego-lay-atman-bay** [comment]
https://python.org

**Comment by SuperHero2010** [comment]
Thank you and I will try tomorrow morning.

**Comment by SuperHero2010** [comment]
Tomorrow morning I will create a new Issues to chat.
