### ISSUE TITLE
Angry

### ISSUE THREAD

**Issue by SuperHero2010** [wmw-modding/wheres-my-editor#5]
> As for fixing wme, I don't think I'm going to, **because I'm planning on creating a new editor, one that can work on android (although I haven't started yet...).**

I just emphasized the bold text so you know. The answer you texted in Issue: "how do i get da pc port of wmw?"

Are you sure you can create "Where's my Editor?" for Android?

**Comment by SuperHero2010** [comment]
What are you doing? Are you busy?

**Comment by SuperHero2010** [comment]
Hey, what are you doing? Why don't you reply? Could it be that you just watch and don't reply?

**Comment by SuperHero2010** [comment]
I'm just asking you to see if you accept or not: Do you want to see the logo I edited?

**Comment by ego-lay-atman-bay** [comment]
Sure why not?

**Comment by SuperHero2010** [comment]
I just want to know if you accept or not.

**Comment by SuperHero2010** [comment]
![wmw_ooze_spout_logo-HD](https://github.com/user-attachments/assets/f0edc65b-155a-4853-8c12-d6b60f41a430)
The word "Ooze Spout" I drew is a bit bad.

**Comment by ego-lay-atman-bay** [comment]
Honestly, I won't accept it (for where's my editor), because I've already cone up with a name for the next wmw editor, "CrankyBox". Plus, I want something a bit higher quality. Sorry.

**Comment by SuperHero2010** [comment]
No. I mean I drew this logo for the game I edit.

**Comment by SuperHero2010** [comment]
I didn't say, "Can you add this logo?" but you did. I just want to know what you think of this logo.

**Comment by ego-lay-atman-bay** [comment]
If it's for your own game, then I guess it's good. You just didn't give any context as to what you were making the logo for before, and so I assumed it was for wme (because you're talking about it here).

**Comment by SuperHero2010** [comment]
I didn't say, "Can you add this logo?" but you did. I just want to know what you think of this logo.

**Comment by SuperHero2010** [comment]
Why do you still think that logo is for wme after I explained?

**Comment by ego-lay-atman-bay** [comment]
No, I now know it's not, I was just explaining why I initially thought it was.

Just to be clear, I know it's not for wme.

**Comment by SuperHero2010** [comment]
I know. At first you thought that logo was for wme. But now you know that logo is for my own game. I was going to tell you why I drew this logo but I think I shouldn't, because I only changed the Ooze spout code and my game is a normal game. And I just want to know how you feel about this logo.

**Comment by SuperHero2010** [comment]
That's just the V1 logo. I also had to make the "Ooze spout" look like raised letters.

**Comment by SuperHero2010** [comment]
Now, do you want me to remove or keep that logo?

**Comment by SuperHero2010** [comment]
> If it's for your own game, then I guess it's good. You just didn't give any context as to what you were making the logo for before, and so I assumed it was for wme (because you're talking about it here).

Wait. Which logo? What was "it"?

**Comment by ego-lay-atman-bay** [comment]
"it" is your logo.

**Comment by SuperHero2010** [comment]
What? I didn't talking about my logo is for WME. WDYM "You just didn't give any context as to what you were making the logo for before"?

**Comment by ego-lay-atman-bay** [comment]
That was before, now I know it's for your game.

**Comment by SuperHero2010** [comment]
> Honestly, I won't accept it (for where's my editor), because I've already cone up with a name for the next wmw editor, "CrankyBox". Plus, I want something a bit higher quality. Sorry.

" "CrankyBox". Plus "?

**Comment by ego-lay-atman-bay** [comment]
It doesn't matter.

**Comment by SuperHero2010** [comment]
Well it doesn't matter. I don't know if you are looking at the error or not. But many errors are bothering me all the time. I'm impatiently waiting for the latest version.

I mean it's because I can't stand it, I don't want to post it right now.

**Comment by ego-lay-atman-bay** [comment]
I am currently not looking at any errors, because I am working on other unrelated projects. You cannot expect any new version anytime soon, so be patient. Heck, I don't know if I'll even fix the errors at all (not because of you). That's how much you cannot expect from me.

**Comment by SuperHero2010** [comment]
> I am currently not looking at any errors, because I am working on other unrelated projects. You cannot expect any new version anytime soon, so be patient. Heck, I don't know if I'll even fix the errors at all (not because of you). That's how much you cannot expect from me.

Okay. If that's the case... I won't bother you anymore. Close and end (I'm serious)

**Comment by SuperHero2010** [comment]
> That was before, now I know it's for your game.

Honestly, you didn't explain clearly the question: "What? I didn't talking about my logo is for WME. WDYM "You just didn't give any context as to what you were making the logo for before"?". Don't think just answering like that is enough. Please explain more clearly about the question I asked.

**Comment by ego-lay-atman-bay** [comment]
That was in the past, I already explained it a few times. I guess it's hard for you to understand what I said.

Just don't worry about it, you don't need the answer you're looking for.

**Comment by SuperHero2010** [comment]
I understand your short answer, but you're saying I created the WME logo before. Meaning: when you first saw my logo, you assumed my logo was for WME and when I said: "Not for WME", you said: "You just didn't give any context as to what you were making the logo for before, and so I assumed it was for wme (because you're talking about it here)". I told you so many times but you still give short explanations and don't read the messages above.

Please tell me the real answer in question: "What? I didn't talking about my logo is for WME. WDYM: "You just didn't give any context as to what you were making the logo for before"?"

**Comment by ego-lay-atman-bay** [comment]
When you first showed your logo, you did not tell me what it was for, so I assumed it was for WME.

I shouldn't need to explain this, because I have already told you that I now know what it's for, that's what matters, not prying for an explanation of what "you didn't give enough context" means (if you don't know what "context" means, search it up). 

As a side note, I am kind of getting a little frustrated with you. Github issues should only be used for bugs in the program, and questions about using wme, not for chatting (like what we're doing right now). Chatting is what the [discussions tab](https://github.com/orgs/wmw-modding/discussions) is for (and I have turned on notifications for it, so I will (hopefully) see messages there).

I am also frustrated with you, because you keep bugging me to fix some problems in wme, and prying for an explanation of something I said weeks ago. Bugging me about problems in wme will not do anything, I will get to them when I get to them, not when you repeatedly bug me about it (in fact, that demotivates me to do it). Prying for an explanation of something I said weeks ago is pretty stupid, because if you didn't get a satisfactory answer, you're probably never going to get one. Plus, the reason I haven't really explained it before, is because it does not matter, and you should be able to understand it. Heck, go ask chatgpt what it means, and it'll probably tell you.

**Comment by SuperHero2010** [comment]
YOU'RE FORCE ME

**Comment by SuperHero2010** [comment]
I lost calm, angry and unable to think so I shouted you like that. It is really not related to ChatGPT. I messaged "Discussion" but you didn't respond. That's why I just messaged "Issue"

I'm disappointing with you. Who bothered and frustrated you? Because you didn't explain clearly, I had to do this. My job isn't a joke. If you had explained clearly earlier, I wouldn't have messaged you continuously. You were frustrated with me, so I got angry. I have reminded you many times: "You should read the messages above if I change or you forget to read" but you haven't listened. As for the 2 errors in Issue: Error III. You can review and fix those 2 errors if you complete other projects.

**Comment by ego-lay-atman-bay** [comment]
I didn't respond in "discussions", because I didn't have notifications on, however that has changed, and I now get notifications.

**Comment by SuperHero2010** [comment]
You're angry so why are you tell me? Let me know you're angry with me?

**Comment by ego-lay-atman-bay** [comment]
I'm not angry, I'm more annoyed and frustrated. I'm telling you, so you can try to do better, and not frustrate me (or anyone else you talk to). It's important to be able to take feedback and apply it.

**Comment by SuperHero2010** [comment]
It's no different than being angry inside (Don't angry me).
