### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by SuperHero2010** [wmw-modding/wheres-my-editor#6]
Sorry last time. It's done. But it shows this error:
![Error](https://github.com/wmw-modding/wheres-my-editor/assets/156646084/6cb5da8c-d875-4409-bf5f-9816de1d0f71)
Am I missing a command or files?

**Comment by SuperHero2010** [comment]
What are you doing? Would you reply me?

**Comment by ego-lay-atman-bay** [comment]
I was sleeping. What you need is to install setuptools, so
```
pip install setuptools
```

**Comment by SuperHero2010** [comment]
I shouldn't have bothered you while you were sleeping yesterday. Is this right?
![2](https://github.com/wmw-modding/wheres-my-editor/assets/156646084/fa9010a7-2263-4fb8-a20a-23a3aa5cd594)

**Comment by SuperHero2010** [comment]
I know the error is in "Save" and "Save as". So I have to study the application build code to fix this error.

**Comment by ego-lay-atman-bay** [comment]
That seems fine. I don't know what's wrong.

You don't actually have to build the exe to run wme, you just need to run
```
cd src
python main.py
```
(the `cd` is just to go into the `src` folder, you don't need to run that if you're already in it).

> I shouldn't have bothered you while you were sleeping

Oh no, that's quite alright. I can always just answer you when I wake up.

**Comment by ego-lay-atman-bay** [comment]
> I know the error is in "Save" and "Save as". So I have to study the application build code to fix this error.

Actually, the error is in [wmwpy](https://github.com/wmw-modding/wmwpy), because that handles all the level saving code.

**Comment by SuperHero2010** [comment]
Looks like WME version 2.3.3. Ok, I'm going to study the wmwpy code.

**Comment by SuperHero2010** [comment]
I check the code "WMW.py" in the path: "D:\Downloads\Data\Python\Lib\site-packages\wmwpy\object_packs" and it still has "StarType". I must have accessed the wrong code.

**Comment by ego-lay-atman-bay** [comment]
Honestly I'm not even sure if I've already fixed the issue, lol. Also, that's not actually where it determines which properties to save, it's in [classes/level.py](https://github.com/wmw-modding/wmwpy/blob/main/src/wmwpy/classes/level.py).

**Comment by SuperHero2010** [comment]
It will take me a long time to fix this error.

**Comment by SuperHero2010** [comment]
I found "Save" and "Save As" in the path: "C:\Users\htbavi\Documents\GitHub\wheres-my-editor\src\main.py".
It took me a long time to find the error.

**Comment by ego-lay-atman-bay** [comment]
Actually, I did some digging, and realized that all you have to do is add this to the `star` class in `object_packs/WMW.py` in wmwpy.

```python
def ready_properties(self):
    return super().ready_properties(include = [
        'StarType',
    ])
```

Just remember to fix the indents (python will throw an error if you don't).

(Honestly, I think I might add it myself, but I would also have to fix a few other things before publishing a new version...)

**Comment by SuperHero2010** [comment]
That is, " Name = 'Star' "?

**Comment by ego-lay-atman-bay** [comment]
Yes

**Comment by SuperHero2010** [comment]
Paste in the part below the "Yellow {}"? (Microsoft VS Code)

**Comment by SuperHero2010** [comment]
I won't ask you much.

**Comment by ego-lay-atman-bay** [comment]
Yeah

**Comment by SuperHero2010** [comment]
It always shows up in red even though I pasted it like you said.

**Comment by ego-lay-atman-bay** [comment]
You have to add an indent (four spaces before every line). The quickest way to do this is by selecting it, and then pressing tab.

**Comment by SuperHero2010** [comment]
Still red.

**Comment by ego-lay-atman-bay** [comment]
Can you send a screenshot?

**Comment by SuperHero2010** [comment]
![3](https://github.com/wmw-modding/wheres-my-editor/assets/156646084/c0e35f1c-e7cd-41ba-8227-d4e2ea9c1149)
I was wrong.

**Comment by ego-lay-atman-bay** [comment]
Oh, that's too many indents. The `def` should line up with the `}`.

**Comment by SuperHero2010** [comment]
Ok. I don't want to bother you by asking too many questions.

**Comment by ego-lay-atman-bay** [comment]
I just want to say, I'm sorry how I acted yesterday. I got annoyed, and was not very helpful. I should've just actually tried to help by explaining how to set it up much clearer than I did in the readme.

**Comment by SuperHero2010** [comment]
I try original app.

**Comment by SuperHero2010** [comment]
![4](https://github.com/wmw-modding/wheres-my-editor/assets/156646084/7fb153cb-1a76-4a47-b61b-deeff0d7d1ff)
Still missing "StarType"

**Comment by SuperHero2010** [comment]
But when I use the new application, it has "StarType"

**Comment by SuperHero2010** [comment]
This is a experiment. You try it: https://github.com/SuperHero20101/wheres-my-editor

**Comment by SuperHero2010** [comment]
I've updated to version 1.0.1. You try it: https://github.com/SuperHero20101/wheres-my-editor

**Comment by ego-lay-atman-bay** [comment]
I've updated wme, with fixing the `StarType` property being kept in the level.

**Comment by SuperHero2010** [comment]
Why you closed my issues?

**Comment by ego-lay-atman-bay** [comment]
To be truthful, this technically should've been an issue, I was just being nice keeping it open. You can ask questions here https://github.com/orgs/wmw-modding/discussions.

I closed this because I fixed the issue you were trying to fix.

**Comment by SuperHero2010** [comment]
Ok. Thanks.

**Comment by SuperHero2010** [comment]
Can you answer my question following the link: "https://github.com/orgs/wmw-modding/discussions/1?sort=old"?

**Comment by SuperHero2010** [comment]
New 1.0.2 version: https://github.com/SuperHero2010/wheres-my-editor
