### ISSUE TITLE
wmw-modding/wheres-my-editor/Development/Setup/5.Create wme virtual environment

### ISSUE THREAD

**Issue by SuperHero2010** [wmw-modding/wheres-my-editor#7]
Last time I tried, it showed an error. Now, how can I paste the command in step 5?

**Comment by ego-lay-atman-bay** [comment]
Sorry, I was busy, and I couldn't get around to helping you.

What is the error you got?

You paste each line in the command seperately. The first line is just to go into the `wheres-my-editor` folder (or whatever you named it), the second line creates a virtual environment (venv), and then the third line activates the venv.

**Comment by SuperHero2010** [comment]
Hey, I clone `wheres-my-editor.git`  and `wmwpy.git`  but shows error (The second time I cloned).
I went back to the "WME Test" folder I had cloned the first time and ran the command in step 5. The first two commands were very convenient. But when it comes to the third command in step 5, it shows an error.

**Comment by ego-lay-atman-bay** [comment]
Can you show me the error you're getting? I need the error so I can actually help you.

**Comment by SuperHero2010** [comment]
![20240613_215256](https://github.com/wmw-modding/wheres-my-editor/assets/156646084/353d77dc-b3bf-4bda-8920-a0419f5e83f9)
Error in 3rd command

**Comment by ego-lay-atman-bay** [comment]
That's not what I meant by "show me the error", but I can already guess what the error is.

Try going into the `.venv/Scripts` folder (cd `.venv/Scripts`), then run `activate.bat`.

**Comment by SuperHero2010** [comment]
How can I run `activate.bat`?

**Comment by ego-lay-atman-bay** [comment]
> How can I run `activate.bat`?

Did you figure it out? I honestly didn't see this until now.

**Comment by SuperHero2010** [comment]
![14](https://github.com/wmw-modding/wheres-my-editor/assets/156646084/01b29926-d9b4-44e3-a3a4-92d30067fda5)
Have I activated `activate.bat` correctly?

**Comment by ego-lay-atman-bay** [comment]
That looks correct.

**Comment by SuperHero2010** [comment]
Ok
