### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by SuperHero2010** [wmw-modding/wheres-my-editor#9]
I forget ask you my new error: when save any level, Fluid Converter missing "FluidType". I had to re-edit it so it took a lot of time.
Sorry I forgot to tell you this error.

**Comment by SuperHero2010** [comment]
I send you this picture so you can understand this error better:
![Before + After](https://github.com/wmw-modding/wheres-my-editor/assets/156646084/155b1667-97ad-4777-b838-e8bce75285fd)
If you want to see the text more clearly, download the image and zoom in.

**Comment by SuperHero2010** [comment]
Before save:
![Before](https://github.com/wmw-modding/wheres-my-editor/assets/156646084/efb513c4-303f-4650-bc7a-218c92beb905)
After save:
![After](https://github.com/wmw-modding/wheres-my-editor/assets/156646084/63f683b3-0e84-4645-8aa9-a9271ad877e1)

**Comment by ego-lay-atman-bay** [comment]
Yeah, I see.

**Comment by SuperHero2010** [comment]
Sorry, I forget to tell you my new error

**Comment by SuperHero2010** [comment]
Can you fix the error?

**Comment by ego-lay-atman-bay** [comment]
I'll look into it tomorrow.

**Comment by SuperHero2010** [comment]
Okay. I wait.

**Comment by ego-lay-atman-bay** [comment]
Do all the properties show up in the editor (before you save)?

**Comment by ego-lay-atman-bay** [comment]
I just discovered what the issue was. I thought I had added code to resolve this, but apparently I didn't. Thankfully I was now able to discover the issue, and fix it.

Can you test this version out?
https://github.com/wmw-modding/wheres-my-editor/actions/runs/9726072949/artifacts/1651600274

Oh, I also added a new thing, if you add an object, all it's default properties that would be saved in the level, are automatically added to the object.

**Comment by SuperHero2010** [comment]
> Do all the properties show up in the editor (before you save)?

   Yes

**Comment by SuperHero2010** [comment]
> I just discovered what the issue was. I thought I had added code to resolve this, but apparently I didn't. Thankfully I was now 
able to discover the issue, and fix it.
>
> Can you test this version out?
> https://github.com/wmw-modding/wheres-my-editor/actions/runs/9726072949/artifacts/1651600274
>
> Oh, I also added a new thing, if you add an object, all it's default properties that would be saved in the level, are 
   automatically added to the object.

   WME 2.3.3 again

**Comment by SuperHero2010** [comment]
New Error: Your WME Test can't load level: controlled_thought-JOSE.xml

**Comment by SuperHero2010** [comment]
I try your WME test app.

**Comment by SuperHero2010** [comment]
WME 2.3.3 is even worse than WME 2.3.2 because certain levels can't be loaded.

**Comment by ego-lay-atman-bay** [comment]
What levels can't be loaded?

Oh, and it is still WME 2.3.3, because the code that I modified was in wmwpy, which I increased the version number to 0.5.3-beta.

**Comment by SuperHero2010** [comment]
controlled_thought-JOSE.xml

**Comment by ego-lay-atman-bay** [comment]
Can you send me the log file?

**Comment by SuperHero2010** [comment]
2. catch_and_release.xml

**Comment by SuperHero2010** [comment]
3. LN_GOOD_MORNING.xml

**Comment by SuperHero2010** [comment]
[10:37:16 AM] [INFO] logs/06-30-24_10-37-16.log
[10:37:38 AM] [WARNING] No level to load
[10:38:02 AM] [ERROR] tk error
Traceback (most recent call last):
  File "main.py", line 1775, in __call__
  File "main.py", line 1537, in openLevel
  File "main.py", line 1715, in loadLevel
  File "main.py", line 1406, in updateLevel
  File "wmwpy\classes\level.py", line 156, in PhotoImage
  File "PIL\ImageTk.py", line 109, in __init__
  File "PIL\Image.py", line 1591, in apply_transparency
IndexError: list assignment index out of range
3. LN_GOOD_MORNING

**Comment by SuperHero2010** [comment]
[10:39:30 AM] [INFO] logs/06-30-24_10-39-30.log
[10:40:01 AM] [WARNING] No level to load
[10:40:19 AM] [ERROR] tk error
Traceback (most recent call last):
  File "main.py", line 1775, in __call__
  File "main.py", line 1537, in openLevel
  File "main.py", line 1715, in loadLevel
  File "main.py", line 1406, in updateLevel
  File "wmwpy\classes\level.py", line 156, in PhotoImage
  File "PIL\ImageTk.py", line 109, in __init__
  File "PIL\Image.py", line 1591, in apply_transparency
IndexError: list assignment index out of range
1. controlled_thought-JOSE.xml

**Comment by ego-lay-atman-bay** [comment]
Thanks. Unfortunately I can't look into it until wednesday or thursday, so you'll have to wait a while.

**Comment by SuperHero2010** [comment]
OK. I wait.

**Comment by SuperHero2010** [comment]
[10:44:15 AM] [INFO] logs/06-30-24_10-44-15.log
[10:44:40 AM] [WARNING] No level to load
[10:45:05 AM] [ERROR] tk error
Traceback (most recent call last):
  File "main.py", line 1775, in __call__
  File "main.py", line 1537, in openLevel
  File "main.py", line 1715, in loadLevel
  File "main.py", line 1406, in updateLevel
  File "wmwpy\classes\level.py", line 156, in PhotoImage
  File "PIL\ImageTk.py", line 109, in __init__
  File "PIL\Image.py", line 1591, in apply_transparency
IndexError: list assignment index out of range
2. catch_and_release.xml

**Comment by SuperHero2010** [comment]
I'm sorry because: When I load the original level, it loads. But when I load the edited level, it fails to load.

**Comment by SuperHero2010** [comment]
Maybe something is wrong with the game folder. It's not that your app is so bad.

**Comment by SuperHero2010** [comment]
You don't need to fix this error because I've already found it.

**Comment by SuperHero2010** [comment]
![12](https://github.com/wmw-modding/wheres-my-editor/assets/156646084/68b6aab7-9061-43e2-b462-8ba4cd927289)

**Comment by SuperHero2010** [comment]
In the WME 2.3.3 application I discovered an error: When loading the edited level, it doesn't show the map and objects but shows an empty screen.

**Comment by SuperHero2010** [comment]
I pressed the old WME 2.3.3 by mistake. I try WME-2.3.3-57.

**Comment by SuperHero2010** [comment]
WME-2.3.3-57 has the same error as WME-2.3.3.

**Comment by SuperHero2010** [comment]
Where can I message people in Discord?

**Comment by ego-lay-atman-bay** [comment]
Click (or tap) their profile picture, then click "Message".

**Comment by SuperHero2010** [comment]
I know but I mean the channel in the server.

**Comment by ego-lay-atman-bay** [comment]
Oh, do you mean reply? If you're on mobile, tap and hold the message, and then there should be a button to reply. If you're on desktop/ right click the nessage.

**Comment by SuperHero2010** [comment]
I'm not reply but I mean the channel in the server.

**Comment by ego-lay-atman-bay** [comment]
Just type in the text box at the bottom of the screen, then hit the blue button next to it to send the message...?

**Comment by SuperHero2010** [comment]
![13](https://github.com/wmw-modding/wheres-my-editor/assets/156646084/44132fb5-0d8a-4bcc-92ac-918359bc58ac)

**Comment by ego-lay-atman-bay** [comment]
You click on the channel to go into it, then type a message and send it.

I'm not entirely sure what you're asking, because you're being a little unclear about it.

**Comment by SuperHero2010** [comment]
"Text channels"?

**Comment by ego-lay-atman-bay** [comment]
Yeah

**Comment by SuperHero2010** [comment]
In the WME 2.3.3 application I discovered an error: When loading the edited level, it doesn't show the map and objects but shows an empty screen.

**Comment by SuperHero2010** [comment]
Today is the duration to fix the error.

**Comment by SuperHero2010** [comment]
Or if it's Thursday, you only have 1 day left to fix the error.

**Comment by SuperHero2010** [comment]
If you're too busy, you can extend the duration.

**Comment by ego-lay-atman-bay** [comment]
I found out the reason why you were getting those errors. Try the latest update here https://github.com/wmw-modding/wheres-my-editor/actions

**Comment by SuperHero2010** [comment]
> I found out the reason why you were getting those errors. Try the latest update here https://github.com/wmw-modding/wheres-my-editor/actions

WME 2.3.3 another again

**Comment by SuperHero2010** [comment]
First error: Loading the edited level only shows a empty screen
---> You have fixed it
Second error: Fluid Converter Property: FluidTypeX have been removing after save the level
---> You have fixed it

**Comment by SuperHero2010** [comment]
I'm closing because you've fixed the error.

**Comment by SuperHero2010** [comment]
I'm sorry because I mentioned these 2 errors twice: Here and on Discord
